### ISSUE TITLE
Report a typo not a bug 

### ISSUE THREAD

**Issue by chnliyong** [gobuffalo/mw-csrf#3]
https://github.com/gobuffalo/mw-csrf/blob/master/csrf.go#L219
```go
func unmask(issued []byte) []byte {
	// Issued tokens are always masked and combined with the pad.
	if len(issued) != tokenLength*2 {
		return nil
	}

	// We now know the length of the byte slice.
	otp := issued[tokenLength:]
	masked := issued[:tokenLength]

	// Unmask the token by XOR'ing it against the OTP used to mask it.
	return xorToken(otp, masked)
}
```
The `mask` append the `xor`ed token to `otp`, but the `unmask` func treats `xor`ed at the end.

As the result is the front half `xor` the latter half，the result is right.

**Comment by sio4** [comment]
Indeed, `otp` and `masked` are treated in a reverse order :-) Thanks for letting us know!
